### ISSUE TITLE
API Key / MD5 hash

### ISSUE THREAD

**Issue by dengroy** [SuperSaaS/supersaas-nodejs-api-client#1]
Hi, is there any reason why we can't use API key/secret or MD5 hash (such as in developer documentation: https://www.supersaas.com/info/dev/user_api) to authenticate instead of account name / password?

**Comment by TertiumQuid** [comment]
We are currently internally testing key-based auth (https://github.com/SuperSaaS/supersaas-nodejs-api-client/tree/auth_key), and aim to update the API clients and documentation in the next few weeks. We'll close this issue (so you'll be notified) when the new release is made available. Thanks!

**Comment by TertiumQuid** [comment]
Hi @dengroy , the API key authentication has now been merged into the master branch. Let us know if you have any other feedback.
