### ISSUE TITLE
validateDatetime console log 

### ISSUE THREAD

**Issue by toropov023** [SuperSaaS/supersaas-nodejs-api-client#12]
I believe this console log shouldn't be there:

https://github.com/SuperSaaS/supersaas-nodejs-api-client/blob/master/src/api/validation.js#L43

**Comment by Fjan** [comment]
Thank you for pointing that out, we'll get that removed as soon as possible.

**Comment by Fjan** [comment]
Closed by https://github.com/SuperSaaS/supersaas-nodejs-api-client/pull/13
