### ISSUE TITLE
Everything as empy array

### ISSUE THREAD

**Issue by intersector** [SuperSaaS/supersaas-nodejs-api-client#17]
Hello,
Every schedule related result is an empty array, while i have already added manually data from Dashboard.
e.g: Client.Instance.schedules.list() 
I have already configured my client using api key and username

Does it requires any further config or permissions from dashboard?

Thanks

**Comment by Fjan** [comment]
Hi @intersector can you please contact https://www.supersaas.com/info/feedback with details of the request and the returned result so we can look into it for you?

**Comment by Wijnand** [comment]
Hi @intersector thank you for your report.  This sounds entirely like you copied the literal example from the README, including the dryRun: true option. If you would set that to false (and I would suggest setting verbose to false as well) you should get results.

**Comment by intersector** [comment]
> 
> 
> Hi @intersector thank you for your report. This sounds entirely like you copied the literal example from the README, including the dryRun: true option. If you would set that to false (and I would suggest setting verbose to false as well) you should get results.

I forgot to mention that i tried with  dryrun:false, but i didnt try with verbose false. I will try and i will post here if the problem persists.

**Comment by intersector** [comment]
Well i tried all options the problem persists. If you cant reproduce the problem and there isnt a dashboard privacy related option, then its probably problem with my installation.

**Comment by Wijnand** [comment]
Hi @intersector, ok for privacy and security reasons I will contact you via email since we are not sure if its something account related or not.

**Comment by intersector** [comment]
> Hi @intersector, ok for privacy and security reasons I will contact you via email since we are not sure if its something account related or not.

Thank you for helping me out. I will try later again to confirm  if everything gone smooth

**Comment by Wijnand** [comment]
This has been resolved now.
