### ISSUE TITLE
schedules.list returns array of undefined

### ISSUE THREAD

**Issue by loke202** [SuperSaaS/supersaas-nodejs-api-client#3]
Hi, when I try and use the the Client.Instance.schedules.list call to to fetch schedules, I get an array with an undefined element( [ undefined ]). This happens in spite of the fact that with verbose set to true the array of tuples is correctly printed to the console by the Client code.  Any help would be greatly appreciated.

**Comment by Fjan** [comment]
Hi @loke202, thank you for reporting this. The developer of the node client just left our company, so it may take us some time to look into this. The module is a pretty thin wrapper around our API, so in this case a simple GET request to the endpoint supersaas.com/api/schedules should give you the same result, see the docs [here](https://www.supersaas.com/info/dev/information_api)

**Comment by TertiumQuid** [comment]
Hey Jan! I can't take a look until later this evening (busy day: deployment
to hospital), but I'll check it out then.

Cheers,

-t

**Comment by nikhil88877** [comment]
> Hi @loke202, thank you for reporting this. The developer of the node client just left our company, so it may take us some time to look into this. The module is a pretty thin wrapper around our API, so in this case a simple GET request to the endpoint supersaas.com/api/schedules should give you the same result, see the docs [here](https://www.supersaas.com/info/dev/information_api)

**Comment by Fjan** [comment]
Closed by https://github.com/SuperSaaS/supersaas-nodejs-api-client/pull/4
