### ISSUE TITLE
Appointments.available - Slots returned data lost trying to map it

### ISSUE THREAD

**Issue by ivansifuentes** [SuperSaaS/supersaas-nodejs-api-client#6]
Trying to retrieve available slots gets an empty array. Running on verbose mode shows the server is returning data:
_Response:
{"slots":[{"id":26679934,"start":"2019-06-20T10:00","finish":"2019-06-20T11:00","title":"Yoga","description":"yoga fire","location":"","count":5} ,.... {"id":26679943,"start":"2019-08-22T10:00","finish":"2019-08-22T11:00","title":"Yoga","description":"yoga fire","location":"","count":5}]}
==============================_

Placing some logs I've managed to blame the issue on this function
https://github.com/SuperSaaS/supersaas-nodejs-api-client/blob/0fcb9faed53bceb695e909fc1f6d6c2320c98792/src/api/Appointments.js#L50

cause it receives the above data, but instead of an array of `Slot`, it returns an empty array.

**Comment by Fjan** [comment]
Thank you for reporting this. Fixed by 48105fa4d4eb53ed9da2ac51c8b26ce1911b739e
Pushed to npm as 1.02
